### ISSUE TITLE
勾选use Exhemtai 后获取数据失败

### ISSUE THREAD

**Issue by moyushang** [nonpricklycactus/Ehentai_metadata#1]
下面填cookie并无 "igneous"  能填

**Comment by LemonSoda-RPG** [comment]
我也遇到了同样的问题

**Comment by name8102** [comment]
我擅自修改了一点代码，添加了输入 igneous 的选项，解决了这个问题

`        ExHentai_Cookies = [{'name':'ipb_member_id', 'value':self.prefs['ipb_member_id'], 'domain':'.exhentai.org', 'path':'/'},
                            {'name':'ipb_pass_hash', 'value':self.prefs['ipb_pass_hash'], 'domain':'.exhentai.org', 'path':'/'},
                            {'name':'igneous','value':self.prefs['igneous'], 'domain':'.exhentai.org', 'path':'/'}]`
`    options = (
        Option('Use_Exhentai','bool',False,_('Use Exhentai'),
               _('If Use Exhentai is True, the plugin will search metadata on exhentai.')),
        Option('ipb_member_id','string',None,_('ipb_member_id'),
               _('If Use Exhentai is True, please input your cookies.')),
        Option('ipb_pass_hash','string',None,_('ipb_pass_hash'),
               _('If Use Exhentai is True, please input your cookies.')),
        Option('igneous','string',None,_('igneous'),
               _('If Use Exhentai is True, please input your cookies.'))
               )`
就是在这两处添加了 igneous
下面是我改好的文件
[__init__.txt](https://github.com/nonpricklycactus/Ehentai_metadata/files/7464807/__init__.txt)

**Comment by nonpricklycactus** [comment]
添加了igneous值，问题已解决。我一般看到问题了都会解决，有问题都可以提
