### ISSUE TITLE
[BUG] Ehentai 搜索url改变导致插件失效

### ISSUE THREAD

**Issue by name8102** [nonpricklycactus/Ehentai_metadata#10]
插件生成的搜索链接失效，目前只有使用 accurate_url 后才可获取元数据。

主要问题是本子类型的搜索改了，现在使用 `f_cats`  来标识要搜索的分类，我直接删掉默认就是搜索全部分类。

此外我还删了一些不知道干什么用的高级搜索，将 `q_dict` 改成了下面这样，插件回复可用。
`q_dict = {'f_search': q,'advsearch': 1, 'f_sh': 'on'}`

**Comment by name8102** [comment]
现在搜索已删除的图库就只会搜索已经删除的，正常的图库就搜不到了。`f_sh=on` 会导致正常的本子搜不到，最好能加个开关控制，或者先搜索一次失败后自动在已删除的图库中搜索。

**Comment by name8102** [comment]
此外还有一些小 BUG ，当书名或作者包含 - 时会使搜索结果出错；当作者缺失时 calibre 会自动改为“未知”，导致无法搜索到结果；ehentai 搜索时似乎会忽略空格隔开的一位数字，会导致一些系列本结果出错

还有能否控制搜索语言的优先级，比如说先搜索中文，然后是日文和英文，排除掉韩语西班牙语等结果？

**Comment by zerona2018** [comment]
不懂编程的只能看着有没有新版本了。哎呀。绅士站这次改动太要命了。

**Comment by zerona2018** [comment]
看了下，能否将冒号之前的内容不记录啊？以前的那个老插件是不加分类的。虽然我当时希望是只记录 female 后面的就足够了。

**Comment by nonpricklycactus** [comment]
因为最近太忙 我先让插件能使用再说 细节上的改动等我有时间再弄

**Comment by zerona2018** [comment]
感谢了。能用就是最好的了。

刚才试着搜了下 还是有一些无法搜到的情况。
Running identify query with parameters: 
{'title': '不埒な教育', 'authors': ['2vs (椎名鯛)'], 'identifiers': {}, 'timeout': 30} 
Using plugins: E-hentai Galleries (2, 3, 1), Amazon.com (1, 3, 2) 
The log from individual plugins is below 

****************************** E-hentai Galleries (2, 3, 1) ****************************** 
Found 0 results 
Downloading from E-hentai Galleries took 1.5475974082946777 
Failed to get gallery_id and gallery_token!
NoneType: None

No result found.
 query: https://exhentai.org/?f_search=%E4%B8%8D%E5%9F%92%E3%81%AA%E6%95%99%E8%82%B2+2vs+%E6%A4%8E%E5%90%8D%E9%AF%9B+chinese 

用的calibre 是6.5 版本

**Comment by nonpricklycactus** [comment]
使用插件的时候不要勾选Chinese Tags 现在这个功能是报废状态
