### ISSUE TITLE
搜索结果只显示第一个

### ISSUE THREAD

**Issue by StarDust189** [nonpricklycactus/Ehentai_metadata#12]
搜索一个系列的第一个本子的时候，在日志里搜索到11条数据，但是只能选择第一个搜索到的元数据。

如下是日志：
Running identify query with parameters: 
{'title': 'ユメ渡りの女王様', 'authors': ['なか'], 'identifiers': {'ehentai': '1231262_1e7b3018e0_1'}, 'timeout': 30} 
Using plugins: E-hentai Galleries (2, 3, 2) 
The log from individual plugins is below 

****************************** E-hentai Galleries (2, 3, 2) ****************************** 
Found 11 results 
Downloading from E-hentai Galleries took 2.3580992221832275 

--- 
Title               : ユメ渡りの女王様 night 3
Author(s)           : なか
Publisher           : チーズ酵母
Tags                : 女性:性玩具, 女性:口塞, 女性:纯女性⚢, 语言:汉语, 其他:系列作品, 女性:石化, 女性:调教, 女性:束缚, 其他:DL版, 女性:鼻吊钩, 女性:百合, 女性:紧身衣裤, 女性:遮眼布, 女性:乳胶紧身衣, 语言:翻译, 原作:原创, 分类:同人志
Languages           : 中文
Rating              : 2.4
Identifiers         : ehentai:1231262_1e7b3018e0_1 

--- 
Title               : ユメ渡りの女王様
Author(s)           : なか
Publisher           : チーズ酵母
Tags                : 女性:性玩具, 女性:调教, 分类:同人志, 女性:束缚, 女性:紧身衣裤, 其他:DL版, 女性:遮眼布, 女性:口塞, 女性:乳胶紧身衣, 女性:纯女性⚢, 语言:汉语, 女性:真空床, 原作:原创, 女性:百合
Languages           : 中文
Rating              : 2.4
Identifiers         : ehentai:1231258_4194908fe1_1 

--- 
Title               : ユメ渡りの女王様 night 10
Author(s)           : なか
Publisher           : チーズ酵母
Tags                : 翻译者:UPPER重工x我不看本子个人汉化, 分类:同人志, 女性:紧身衣裤, 其他:DL版, 女性:乳胶紧身衣, 女性:纯女性⚢, 语言:汉语, 其他:系列作品, 语言:翻译, 原作:原创, 女性:百合
Languages           : 中文
Rating              : 2.2
Identifiers         : ehentai:2437818_7d7065b57e_1 

--- 
Title               : ユメ渡りの女王様 night 9
Author(s)           : なか
Publisher           : チーズ酵母
Tags                : 分类:同人志, 女性:马尾辫, 女性:束缚, 女性:史莱姆女孩, 翻译者:阿卡姆汉化, 女性:紧身衣裤, 其他:DL版, 女性:乳胶紧身衣, 女性:口塞, 女性:纯女性⚢, 语言:汉语, 其他:系列作品, 语言:翻译, 原作:原创, 女性:魔物娘, 女性:百合
Languages           : 中文
Rating              : 2.3
Identifiers         : ehentai:2167968_9a48241243_1 

--- 
Title               : ユメ渡りの女王様 night 4
Author(s)           : なか
Publisher           : チーズ酵母
Tags                : 女性:萝莉, 女性:性玩具, 女性:女性主导, 女性:纯女性⚢, 其他:系列作品, 语言:英语, 女性:调教, 女性:束缚, 女性:水下, 其他:DL版, 女性:死库水, 翻译者:Panatical, 女性:百合, 女性:双马尾, 女性:紧身衣裤, 女性:乳胶紧身衣, 语言:翻译, 原作:原创, 分类:同人志
Languages           : 英语
Rating              : 2.1
Identifiers         : ehentai:2138873_4201afb380_1 

--- 
Title               : ユメ渡りの女王様 night 8
Author(s)           : なか
Publisher           : チーズ酵母
Tags                : 女性:真空床, 分类:同人志, 女性:束缚, 翻译者:阿卡姆汉化, 女性:双马尾, 女性:紧身衣裤, 其他:DL版, 女性:乳胶紧身衣, 女性:口塞, 其他:无插入, 女性:纯女性⚢, 语言:汉语, 其他:系列作品, 语言:翻译, 原作:原创, 女性:百合
Languages           : 中文
Rating              : 2.3
Identifiers         : ehentai:1980829_ca53d19fea_1 

--- 
Title               : ユメ渡りの女王様 night 7
Author(s)           : なか
Publisher           : チーズ酵母
Tags                : 分类:同人志, 女性:束缚, 女性:史莱姆女孩, 翻译者:阿卡姆汉化, 女性:紧身衣裤, 其他:DL版, 女性:乳胶紧身衣, 女性:口塞, 女性:纯女性⚢, 语言:汉语, 女性:挠痒, 其他:系列作品, 语言:翻译, 原作:原创, 女性:百合
Languages           : 中文
Rating              : 2.3
Identifiers         : ehentai:1715117_b9cbf0c6ae_1 

--- 
Title               : ユメ渡りの女王様 night 6
Author(s)           : なか
Publisher           : チーズ酵母
Tags                : 分类:同人志, 女性:史莱姆女孩, 翻译者:阿卡姆汉化, 女性:紧身衣裤, 其他:DL版, 女性:女性主导, 女性:口塞, 女性:接吻💏, 女性:纯女性⚢, 女性:乳胶紧身衣, 语言:汉语, 其他:系列作品, 语言:翻译, 原作:原创, 女性:百合
Languages           : 中文
Rating              : 2.3
Identifiers         : ehentai:1678655_2a967e17d1_1 

--- 
Title               : ユメ渡りの女王様 night 5
Author(s)           : なか
Publisher           : チーズ酵母
Tags                : 分类:同人志, 女性:束缚, 翻译者:靴下汉化组, 女性:紧身衣裤, 其他:DL版, 女性:女性主导, 女性:舔足, 女性:口塞, 女性:纯女性⚢, 女性:乳胶紧身衣, 语言:汉语, 其他:系列作品, 语言:翻译, 原作:原创, 女性:眼镜👓, 女性:百合
Languages           : 中文
Rating              : 2.3
Identifiers         : ehentai:1617757_c36614739f_1 

--- 
Title               : ユメ渡りの女王様 Client Side
Author(s)           : なか
Publisher           : チーズ酵母
Tags                : 分类:同人志, 翻译者:靴下汉化组, 女性:紧身衣裤, 其他:DL版, 女性:乳胶紧身衣, 女性:纯女性⚢, 语言:汉语, 其他:系列作品, 语言:翻译, 原作:原创, 女性:百合
Languages           : 中文
Rating              : 2.3
Identifiers         : ehentai:1459018_0810e34554_1 

--- 
Title               : ユメ渡りの女王様 night 2
Author(s)           : なか
Publisher           : チーズ酵母
Tags                : 女性:感官共享, 女性:女性主导, 女性:口塞, 女性:纯女性⚢, 其他:系列作品, 语言:英语, 女性:调教, 女性:束缚, 其他:DL版, 女性:换身, 女性:附身, 女性:真空床, 翻译者:英語, 女性:乱交, 女性:油, 女性:百合, 女性:紧身衣裤, 女性:乳胶紧身衣, 原作:原创, 女性:眼镜👓, 分类:同人志
Languages           : 英语
Rating              : 2.2
Identifiers         : ehentai:1373141_c2266d6937_1 

******************************************************************************** 
The identify phase took 2.45 seconds 
The longest time (2.358099) was taken by: E-hentai Galleries 
Merging results from different sources 
We have 1 merged results, merging took: 0.00 seconds

**Comment by StarDust189** [comment]
并且在MAC上管理，使用acculate_label 会报错 
calibre, version 6.24.0
错误： 下载失败: 无法下载元数据。请点击“显示详情”获取更多信息。

Traceback (most recent call last):
  File "calibre/utils/ipc/simple_worker.py", line 53, in run
  File "calibre/utils/ipc/__init__.py", line 24, in eintr_retry_call
  File "multiprocessing/connection.py", line 255, in recv
  File "multiprocessing/connection.py", line 419, in _recv_bytes
  File "multiprocessing/connection.py", line 388, in _recv
EOFError

**Comment by nonpricklycactus** [comment]
元数据获取只能选择第一个，关于想选择元数据只能用acculate_label功能
至于MAC上acculate_label 会报错只能看把calibre升级后再看有没有
毕竟EOFError 通常是进程间通信或数据传输中的问题
