### ISSUE TITLE
勾选use exhentai  cookie填写好的情况下无效

### ISSUE THREAD

**Issue by shaoyangx** [nonpricklycactus/Ehentai_metadata#13]
试验链接：https://exhentai.org/g/1297776/8f211fb492/
问题：
1：在勾选use exhentai后，并填写好ipb member id ，ipb_pass_hash ，igneous三项后，搜索的依然是e-hentai的画廊。
以https://exhentai.org/g/1297776/8f211fb492/为例，e-hentai无中文翻译画廊，只有意大利语的翻译，exhentai中有中文的画廊，在勾选use exhentai后检索的依然是e-hentai的意大利语言翻译。只有使用Accurate Label才能正确获取里画廊的TAG。
2：语言标签似乎有点问题，还是以上述链接为例，通过URL获取画廊TAG后， 汉语的标签并没有正确识别成语言的中文，而是依旧存在于标签栏的语言：汉语

建议：能否使用正则替换获取后的标签，将 女性:XXX  替换为  女性.XXX 。Calibre中的标签分组是按照.识别的，画廊的则是:，这样获取就不需要在替换规则里添加替换了。

**Comment by nonpricklycactus** [comment]
你先试下勾选Accurate_Label，输入链接来获取tag试试，有可能是搜索不准确导致的

**Comment by nonpricklycactus** [comment]
这个链接似乎失效了，你把对应的本子名称发过来看下 
对于语言栏数据修改部分 和 标签替换部分 之后有空我再看看

**Comment by shaoyangx** [comment]
(C94) [灯色の研究室 (灯問)] NeuTRal Actor [中国翻訳]
这是本子名字，我看着没有失效啊？这是里站的链接。
之前出去就一段时间，没用电脑。。

**Comment by nonpricklycactus** [comment]
我这边点链接显示不存在，我直接搜名字试试
















在 2023-12-09 03:48:46，"shaoyangx" ***@***.***> 写道：

(C94) [灯色の研究室 (灯問)] NeuTRal Actor [中国翻訳]
这是本子名字，我看着没有失效啊？这是里站的链接。
之前出去就一段时间，没用电脑。。
