### ISSUE TITLE
Fail to get metadata due to IP was banned or requests too frequently

### ISSUE THREAD

**Issue by mslxl** [nonpricklycactus/Ehentai_metadata#15]
## Version
Calibre: 7.10.0 on windows11
Ehentai_metadata: 2.3.3

## Config
Here is my config:

| Plugin Config | Metadata Download Config|
|:-:|:-:|
| ![image](https://github.com/nonpricklycactus/Ehentai_metadata/assets/11132880/6acf2fce-035f-45f7-a779-cd059553729f) | ![image](https://github.com/nonpricklycactus/Ehentai_metadata/assets/11132880/ac01432d-1f5a-4d00-815f-f0b0f9d9d3dc) |

Http Proxy was enabled on 20171 port

## Reproduction method:
1. ![image](https://github.com/nonpricklycactus/Ehentai_metadata/assets/11132880/298d3998-3294-449d-b142-1391af7957e5)
Click `Download metadata and covers`
2. Click `Download only metadata`
3. ![image](https://github.com/nonpricklycactus/Ehentai_metadata/assets/11132880/2da88bb6-39e5-41c9-9da4-8dcbcae5580e)
Input URL: https://exhentai.org/g/2649295/af54008829/
4. ![image](https://github.com/nonpricklycactus/Ehentai_metadata/assets/11132880/61e079a4-7d06-44dc-b881-4c64282d1201)
Gets failure

It seems that `Accurate_Label` does not work

## Logs

```
#################### Log for 龍神さまの嫁入り [中国翻訳] [DL版] ####################
Running identify query with parameters: 
{'title': '龍神さまの嫁入り [中国翻訳] [DL版]', 'authors': ['パンダが一匹。 (コミズミコ)'], 'identifiers': {}, 'timeout': 30} 
Using plugins: E-hentai Galleries (2, 3, 3) 
The log from individual plugins is below 

****************************** E-hentai Galleries (2, 3, 3) ****************************** 
Found 0 results 
Downloading from E-hentai Galleries took 3.395373821258545 
{'http': '127.0.0.1:20171', 'https': '127.0.0.1:20171'}
Plugin E-hentai Galleries failed
Traceback (most recent call last):
  File "calibre\ebooks\metadata\sources\identify.py", line 47, in run
  File "calibre_plugins.dummy1.__init__", line 695, in identify
  File "calibre_plugins.dummy1.__init__", line 540, in get_all_details
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 

******************************************************************************** 
The identify phase took 3.41 seconds 
The longest time (3.395374) was taken by: E-hentai Galleries 
Merging results from different sources 
We have 0 merged results, merging took: 0.00 seconds 
Failed to download metadata for 龍神さまの嫁入り [中国翻訳] [DL版] 
```

**Comment by mslxl** [comment]
![image](https://github.com/nonpricklycactus/Ehentai_metadata/assets/11132880/55fe9d85-2d72-4c47-be18-7b8892878ee5)

It's my fault :(, but I think the plugin should tells user when met this error

**Comment by mslxl** [comment]
| | |
|:-:|:-:|
|The response body of `exhentai.org` when request it too frequently | ![image](https://github.com/nonpricklycactus/Ehentai_metadata/assets/11132880/55fe9d85-2d72-4c47-be18-7b8892878ee5) |
| The response body of `api.e-hentai.org` when request it quickly| ![image](https://github.com/nonpricklycactus/Ehentai_metadata/assets/11132880/4568bfec-6b81-4162-a8b5-271af7b7fbcb) |
| The response body of `api.e-hentai.org` when request it too frequently | ![image](https://github.com/nonpricklycactus/Ehentai_metadata/assets/11132880/fb544a77-3b9e-46b1-b4ee-bb2849df8554) |

If IP requests the host too frequently that, all hosts will return an HTTP page that contains `Your IP address has been temporarily banned for excessive pageloads`.
But if an IP requests `api.e-hentai.org` quickly and the IP is unbanned, `api.e-hentai.org` will response with HTTP 200 and empty HTTP body merely.

For banned IP, there is no way to solve, it needs time to unban from host, while for `api.e-hentai.org`, **retrying after few seconds** is a good way to retrieve data.

How about add these features to the plugins:
1. Notifies users when they are banned.
2. Enables the plugin to retry when an empty message is received.

**Comment by nonpricklycactus** [comment]
This is a small script, and I don't want it to become too complicated. For IP bans caused by frequent scraping, you can use third-party proxy tools to solve the problem, or manually change your IP after an IP ban.
