### ISSUE TITLE
部分本被删，但是通过第三方插件还是能根据网址获取标签。

### ISSUE THREAD

**Issue by moyushang** [nonpricklycactus/Ehentai_metadata#3]
例：https://exhentai.org/g/1380610/7f61fc06a7/
![屏幕截图 2022-04-04 014715](https://user-images.githubusercontent.com/49310378/161441556-f833b471-16f3-4631-9868-5d6b29b56a00.png)
通过Tampermonkey插件能正常打开不跳转

能否弄一个把info.json转换为calibre 标签带翻译的插件
[info.json.txt](https://github.com/nonpricklycactus/Ehentai_metadata/files/8405198/info.json.txt)

**Comment by nonpricklycactus** [comment]
可以通过最新功能输入链接直接获取
勾选 Accurate_Label功能，点下载元数据，输入地址就可以了
