### ISSUE TITLE
关于数据库翻译的问题

### ISSUE THREAD

**Issue by moyushang** [nonpricklycactus/Ehentai_metadata#4]
翻译数据库更新后,部分标签有新翻译
之前已经录入标签的该怎么处理
全部再下一次元数据工程量太大了.
![例](https://user-images.githubusercontent.com/49310378/162311264-ef8c250d-663e-4589-aabc-52331083ffca.png)

补充问题:
在有ids情况下,不会按照原ids上网址下载标签,而是重新搜索 ,出现无法获取或获取成其他本的情况
![屏幕截图 2022-04-08 052008](https://user-images.githubusercontent.com/49310378/162316828-71ce2332-8d95-4640-927c-c849a0bb42c7.png)

![屏幕截图 2022-04-08 052611](https://user-images.githubusercontent.com/49310378/162320632-b358f7b6-96a6-4c3f-aad5-f9cf2b2edb3f.png)

书名识别还有些问题
[新建文本文档 (8).txt](https://github.com/nonpricklycactus/Ehentai_metadata/files/8447970/8.txt)

**Comment by moyushang** [comment]
![屏幕截图 2022-04-08 052008](https://user-images.githubusercontent.com/49310378/162316611-72fb0296-2789-4f0e-a7f3-0f649882d6ff.png)

**Comment by nonpricklycactus** [comment]
这种特殊情况一般就自己手动修改就好了，这些情况要修改代码的话挺麻烦的，要等有空才行。
部分标签有新翻译可以在calibre的标签映射器中自己配置一下翻译就行
对于ids的情况只能勾选Accurate_Label功能手动输入链接来精确获取

**Comment by nonpricklycactus** [comment]
关于'&' 变成 '&amp;' 的情况已经解决了，重新下载一下2.2.3版本就行
