### ISSUE TITLE
[BUG] 存在多个画师和社团时只会添加一个

### ISSUE THREAD

**Issue by name8102** [nonpricklycactus/Ehentai_metadata#6]
大概看了一下，发现问题是 `j=0` 放到了循环里面，导致每个新作者都会把原来的覆盖，只添加了最后一个，改出去就可以正常添加多个作者。奇怪的是修改后语言不能添加了。

多个社团没有什么好办法，calibre 的出版社只能有一个，或许多于一个的社团只能用 tag 来保存。

**Comment by nonpricklycactus** [comment]
可以添加多个出版社添加方法类似authors 
你的这个问题已经解决了  你可以在v2.3.0版本看到它
